# Generated by Django 6.0.1 on 2026-02-02 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0005_alter_dispositivos_patrimonio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id_observacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('Dispositivo', 'Dispositivo'), ('Laboratorio', 'Laboratorio')], default='Dispositivo', max_length=255)),
                ('observacao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('id_dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='laboratorios.dispositivos')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='laboratorios.laboratorio')),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
