# Generated by Django 5.1.1 on 2024-10-08 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('sala_ou_bloco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('patrimonio', models.CharField(max_length=255)),
                ('is_computador', models.BooleanField(default=False)),
                ('configuracao', models.TextField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('data_verificacao', models.DateField()),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='laboratorios.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id_software', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('versao', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='laboratorios.dispositivos')),
            ],
        ),
    ]
