# Generated by Django 5.1.1 on 2024-11-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='configuracao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
