# Generated by Django 5.1.1 on 2024-11-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0002_alter_dispositivos_configuracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='status',
            field=models.CharField(choices=[('Funcionando', 'Funcionando'), ('Com Defeito', 'Com Defeito')], default='Funcionando', max_length=50),
        ),
    ]
