# Generated by Django 5.1.1 on 2025-01-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0003_alter_dispositivos_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivos',
            old_name='marca',
            new_name='tipo',
        ),
    ]
