# Generated by Django 5.1.1 on 2025-10-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0004_rename_marca_dispositivos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='patrimonio',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
