# Generated by Django 5.1.1 on 2025-01-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0002_observacao_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacao',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='observacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('resolvido', 'Resolvido')], default='pendente', max_length=15),
        ),
    ]
