# Generated by Django 5.1.1 on 2025-02-01 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0003_observacao_prioridade_observacao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacao',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='observacao',
            name='status',
        ),
        migrations.AddField(
            model_name='observacao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Dispositivo', 'dispositivo'), ('Laboratorio', 'laboratorio')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='id_usuario',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
