# Generated by Django 5.1.1 on 2025-02-01 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0004_rename_marca_dispositivos_tipo'),
        ('problemas', '0004_remove_observacao_prioridade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacao',
            name='id_dispositivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='laboratorios.dispositivos'),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Dispositivo', 'Dispositivo'), ('Laboratorio', 'Laboratorio')], default='Dispositivo', max_length=255),
        ),
    ]
