# Generated by Django 5.1.1 on 2025-02-01 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0004_rename_marca_dispositivos_tipo'),
        ('problemas', '0005_alter_observacao_id_dispositivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacao',
            name='id_dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='laboratorios.dispositivos'),
        ),
    ]
